### ISSUE TITLE
[Bug] 表示について

### ISSUE THREAD

**Issue by ganyariya** [nikaera/zenn-badge#10]
@nikaera  

こんにちは！
zenn-badge ですが、profile, liks など が 2021/10/30 18:24 時点で `0` と表示されてしまっているようです。

**Comment by nikaera** [comment]
@ganyariya おお！確かに 0 となっていますね。。ご指摘ありがとうございます！確認します！ 🕵️

**Comment by nikaera** [comment]
@ganyariya こちら修正致しました！🙋 お手数なのですがご確認のほどよろしくお願いいたします！🙏. 🙇 
 https://zenn-badge-nikaera.vercel.app/

**Comment by ganyariya** [comment]
@nikaera 

https://zenn-badge-nikaera.vercel.app/　のサイトで likes などの数を確認できました＞＜
修正ありがとうございました！！

**Comment by ganyariya** [comment]
@nikaera 
何度もすいません... (;;)

もしかしたらですが， vercel or 直リンクで badge を開いたときは表示できるのですが，
README 上だとうまく表示されてないかもです．（response の指定形式などでしょうか... ?）

https://zenn-badge-nikaera.vercel.app/
https://github.com/nikaera

**Comment by nikaera** [comment]
@ganyariya 調べてみたところ GitHub 上でも画像をキャッシュしているらしく、下記の `リクエストパラメーターを変更` のやり方を試したところ、無事に更新されたようでした！ ☺️ 
https://web-dev.hatenablog.com/entry/etc/git/github/readme-badges-are-not-updated

↓ で試してみました ✅ 
https://github.com/nikaera

**Comment by ganyariya** [comment]
@nikaera 
ありがとうございます！ GitHub のキャッシュの問題だったのですね...
PURGE のほうを試したところ、x時間経ったら、正の数字を README 上で確認できました！
ありがとうございます＞＜
