### ISSUE TITLE
バッジが表示されない

### ISSUE THREAD

**Issue by antyuntyuntyun** [nikaera/zenn-badge#16]
@nikaera
zenn側のAPI仕様変更影響の理由か何かわからないのですが、いつからかバッジが表示されなくなってしまっています。Github のプロフィールで愛用させていただいているので、可能であれば表示されるように修正いただけると嬉しいです！

**Comment by nikaera** [comment]
@antyuntyuntyun ご連絡ありがとうございます！！こちら表示されるよう修正できたと思うのですがいかがでしょう？？ 💭

**Comment by antyuntyuntyun** [comment]
@nikaera 表示されるようになっていること確認できました！ ご対応ありがとうございます🙏
